### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by alimd** [JrCs/gptsync#2]
Thank you for create and publish this great tools
I use hfsexplorer to explore hfs partition in windows but i have issue after sunc
I synced my macbook disk but i cant see my mac drives in windows (on bootcamp) anymore, because gptsync use a single protected partition for all mac partitions
I need a option to sync mbr with exactly gpt partition
or other tools for roll my mbr table back
thank you

**Comment by JrCs** [comment]
You can only have 3 entries in addition to the protected partition in the MBR.
So you can only select (at max) 3 GPT partitions to be in sync in the mbr scheme.
